name: cameo
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  data_connection_checker: ^0.3.4
  date_range_picker: ^1.0.6
  flutter_secure_storage: ^3.3.5
  flutter_svg: null
  form_field_validator: ^1.0.1
  getwidget: ^1.2.4
  html: ^0.14.0+4
  http: ^0.12.2
  intl: ^0.16.1
  recase: ^3.0.1
  rich_alert: ^0.1.32
  transparent_image: ^1.0.0
  video_player: ^1.0.1
  material_floating_search_bar: ^0.2.6
  provider:
  dio: ^3.0.10
  image_picker: ^0.6.7+22
  file_picker: ^2.1.6
  shimmer: ^1.1.2
  mime_type: ^0.3.2
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.27
  flutter_chat_bubble: ^1.0.2
  cached_network_image: ^2.5.0
  video_thumbnail: ^0.2.5+1
  youtube_player_flutter: ^7.0.0+7
  vimeoplayer: ^0.1.8
  flutter_native_splash: 0.2.9
  get: ^3.26.0
  video_compress: ^2.1.1
  firebase_core: 
  firebase_auth: 
  google_sign_in:
  chewie:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/splashscreen.png
  color: 000000
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
